server:
    port: 9090
    context-path:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ctrip_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      idle-timeout: 10000


mybatis:
    mapperLocations: classpath:/mappers/*.xml