spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ctrip_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      idle-timeout: 10000
